name: 0.1.$(Rev:r)

trigger:
  batch: true
  branches:
    include:
      - master

variables:
  - name: terraform_download_sha
    value: 602d2529aafdaa0f605c06adb7c72cfb585d8aa19b3f4d8d189b42589e27bf11
  - name: terraform_version
    value: 0.12.24
  - name: tf_in_automation
    value: true

stages:
  - stage: Build
    jobs:
      - job: Build

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self
            fetchDepth: 1

          - task: Bash@3
            inputs:
              filePath: './scripts/terraform-download.sh'
            displayName: 'Terraform Download'

#          - task: AzureCLI@1
#            inputs:
#              azureSubscription: 'Azure subscription 1'
#              scriptLocation: 'scriptPath'
#              scriptPath: './scripts/environment-setup.sh'
#              addSpnToEnvironment: true
#              failOnStandardError: true
#            displayName: 'Environment Setup'
